Запускаем test1.py и убеждаемся, что проходят тест с сообщением, тест с флагом и тест с исключением.
В файле result выгрузка из командной строки
